name: comuni_safe_front
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  google_sign_in: ^6.1.6
  http: ^0.13.6
  url_launcher: ^6.1.7
  flutter_secure_storage: ^9.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  google_maps_flutter: ^2.5.0

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google_logo.png
    - assets/logo.png
    - assets/carabineros.png
    - assets/pdi.png
    - assets/prevencion.png
    - assets/samu.png
    - assets/seguridad.png
    - assets/temuco.png
    - assets/contactos-logo.png
    - assets/llamada-carabineros.png
    - assets/llamada-ambulancia.png
    - assets/mapa-logo.png
