name: comuni_safe_front
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9

  google_sign_in: ^6.1.6
  http: ^1.4.0
  url_launcher: ^6.1.7
  flutter_secure_storage: ^9.0.0
  cupertino_icons: ^1.0.8

  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geolocator: ^11.0.0

  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  google_maps_flutter: ^2.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/google_logo.png
    - assets/logo.png
    - assets/carabineros.png
    - assets/pdi.png
    - assets/prevencion.png
    - assets/samu.png
    - assets/seguridad.png
    - assets/temuco.png
    - assets/contactos-logo.png
    - assets/llamada-carabineros.png
    - assets/llamada-ambulancia.png
    - assets/mapa-logo.png
    - assets/microtrafico.png
    - assets/espacios.png
    - assets/robo.png
    - assets/ambulancia.png
