// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvYr0VJuiOZMp51skaZxKlrt7ZktHH3Y0',
    appId: '1:654543001926:web:9bb1d8ae9bab1566f72d47',
    messagingSenderId: '654543001926',
    projectId: 'comunisafe-f8f8d',
    authDomain: 'comunisafe-f8f8d.firebaseapp.com',
    storageBucket: 'comunisafe-f8f8d.firebasestorage.app',
    measurementId: 'G-3KD4YBWNHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Wm2ofFc9fnIk77zQm7WSEUBbzwg90uM',
    appId: '1:654543001926:android:8fde70f71bbfcd63f72d47',
    messagingSenderId: '654543001926',
    projectId: 'comunisafe-f8f8d',
    storageBucket: 'comunisafe-f8f8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh56qTqXrmhblY8RAn87rCKn0F8Bj1Y1s',
    appId: '1:654543001926:ios:20e31aa6838798cbf72d47',
    messagingSenderId: '654543001926',
    projectId: 'comunisafe-f8f8d',
    storageBucket: 'comunisafe-f8f8d.firebasestorage.app',
    iosClientId: '654543001926-4f3pn1hi7uaj5ebginc22ur3o27eaqvs.apps.googleusercontent.com',
    iosBundleId: 'com.example.comuniSafeFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh56qTqXrmhblY8RAn87rCKn0F8Bj1Y1s',
    appId: '1:654543001926:ios:20e31aa6838798cbf72d47',
    messagingSenderId: '654543001926',
    projectId: 'comunisafe-f8f8d',
    storageBucket: 'comunisafe-f8f8d.firebasestorage.app',
    iosClientId: '654543001926-4f3pn1hi7uaj5ebginc22ur3o27eaqvs.apps.googleusercontent.com',
    iosBundleId: 'com.example.comuniSafeFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvYr0VJuiOZMp51skaZxKlrt7ZktHH3Y0',
    appId: '1:654543001926:web:ec2ad54d4f62be5ff72d47',
    messagingSenderId: '654543001926',
    projectId: 'comunisafe-f8f8d',
    authDomain: 'comunisafe-f8f8d.firebaseapp.com',
    storageBucket: 'comunisafe-f8f8d.firebasestorage.app',
    measurementId: 'G-DNVVY0XCDS',
  );
}
